"""move candidate access token out of the RLS-protected table

Revision ID: 48fadadae02f
Revises: 0003_rls
Create Date: 2026-10-08 02:00:42.801705
"""
from alembic import op
import sqlalchemy as sa


revision = '48fadadae02f'
down_revision = '0003_rls'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Credentials move to a table outside row-level security.

    A candidate presents a token before anyone knows their organisation,
    so the lookup cannot be tenant-scoped -- a protected table denies
    the read and the candidate can never authenticate. The new table
    holds only the digest and the link, and everything it unlocks stays
    protected.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_access_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidate_access_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_access_tokens_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_access_tokens_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_access_tokens_token_hash'), ['token_hash'], unique=True)

    # Carry existing credentials across before the old column goes.
    op.execute(
        "INSERT INTO candidate_access_tokens "
        "(token_hash, candidate_id, organisation_id, created_at) "
        "SELECT access_token_hash, id, organisation_id, invited_at FROM candidates"
    )

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_access_token_hash'))
        batch_op.drop_column('access_token_hash')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Carry existing credentials across before the old column goes.
    op.execute(
        "INSERT INTO candidate_access_tokens "
        "(token_hash, candidate_id, organisation_id, created_at) "
        "SELECT access_token_hash, id, organisation_id, invited_at FROM candidates"
    )

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_token_hash', sa.VARCHAR(length=64), nullable=False))
        batch_op.create_index(batch_op.f('ix_candidates_access_token_hash'), ['access_token_hash'], unique=1)

    with op.batch_alter_table('candidate_access_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_access_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_candidate_access_tokens_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_access_tokens_candidate_id'))

    op.drop_table('candidate_access_tokens')
    # ### end Alembic commands ###
