"""assessment domain: candidates, attempts, scores, references

Revision ID: ccfccc3f9fc9
Revises: ba3db9442960
Create Date: 2026-10-08 01:08:16.772352
"""
from alembic import op
import sqlalchemy as sa


revision = 'ccfccc3f9fc9'
down_revision = 'ba3db9442960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('access_token_hash', sa.String(length=64), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organisation_id', 'email', name='uq_candidate_org_email')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_access_token_hash'), ['access_token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_candidates_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('training_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lineage_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('forked_from_lineage_id', sa.String(length=64), nullable=True),
    sa.Column('organisation_id', sa.Integer(), nullable=True),
    sa.Column('construct_id', sa.String(length=64), nullable=False),
    sa.Column('unit_code', sa.String(length=32), nullable=False),
    sa.Column('unit_title', sa.String(length=300), nullable=False),
    sa.Column('qualification_title', sa.String(length=300), nullable=True),
    sa.Column('career_path', sa.String(length=300), nullable=True),
    sa.Column('training_gov_url', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('review_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_references', schema=None) as batch_op:
        batch_op.create_index('ix_reference_lineage', ['lineage_id', 'version'], unique=False)
        batch_op.create_index('ix_reference_lookup', ['construct_id', 'is_current', 'organisation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_references_construct_id'), ['construct_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_references_is_current'), ['is_current'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_references_lineage_id'), ['lineage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_references_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('assessment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('PRACTICE', 'FORMAL', name='attemptmode', native_enum=False, length=16), nullable=False),
    sa.Column('item_set', sa.String(length=32), nullable=False),
    sa.Column('engine_config_version', sa.String(length=32), nullable=False),
    sa.Column('engine_config_digest', sa.String(length=64), nullable=False),
    sa.Column('overall_normalised', sa.Float(), nullable=False),
    sa.Column('overall_band', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_attempts_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_attempts_organisation_id'), ['organisation_id'], unique=False)
        batch_op.create_index('ix_attempt_org_candidate', ['organisation_id', 'candidate_id'], unique=False)

    op.create_table('candidate_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('construct_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'construct_id', name='uq_assignment_candidate_construct')
    )
    with op.batch_alter_table('candidate_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_assignments_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('attempt_construct_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('construct_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('normalised', sa.Float(), nullable=False),
    sa.Column('band', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['assessment_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'construct_id', name='uq_score_attempt_construct')
    )
    with op.batch_alter_table('attempt_construct_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_construct_scores_attempt_id'), ['attempt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt_construct_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_construct_scores_attempt_id'))

    op.drop_table('attempt_construct_scores')
    with op.batch_alter_table('candidate_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_assignments_candidate_id'))

    op.drop_table('candidate_assignments')
    with op.batch_alter_table('assessment_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_org_candidate')
        batch_op.drop_index(batch_op.f('ix_assessment_attempts_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_assessment_attempts_candidate_id'))

    op.drop_table('assessment_attempts')
    with op.batch_alter_table('training_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_references_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_training_references_lineage_id'))
        batch_op.drop_index(batch_op.f('ix_training_references_is_current'))
        batch_op.drop_index(batch_op.f('ix_training_references_construct_id'))
        batch_op.drop_index('ix_reference_lookup')
        batch_op.drop_index('ix_reference_lineage')

    op.drop_table('training_references')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_organisation_id'))
        batch_op.drop_index(batch_op.f('ix_candidates_access_token_hash'))

    op.drop_table('candidates')
    # ### end Alembic commands ###
